# Generated by Django 4.2.14 on 2024-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='avartar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
