# Generated by Django 4.2.14 on 2024-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_customeruser_countrty_customeruser_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('building', 'Building'), ('land', 'Land'), ('apartment', 'Apartment')], max_length=50)),
            ],
        ),
    ]
